version: '3'
services:
  ulms-nginx:
    container_name: "ulms-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - ulms-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  ulms-app:
    container_name: "ulms-app"
    build:
      context: ./docker/php
    depends_on:
      - ulms-db
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  ulms-db:
    image: mysql:8.0.33
    command: --max_allowed_packet=32505856
    container_name: "ulms-db"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ulms_db
    ports:
      - 3306:3306

  ulms-redis:
    image: redis:alpine
    container_name: "ulms-redis"
    ports:
      - 16379:6379
      
  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    environment: [
      "PMA_ARBITRARY=1", 
      "PMA_HOST=ulms-db",
      "PMA_USER=root",
      "PMA_PASSWORD=root"
    ]
    ports:
      - 3000:80
    volumes:
      - ./phpadmin/sessions:/sessions
